<?php

namespace Database\Seeders;

use App\Models\MiembroComision;
use Illuminate\Database\Seeder;

class MiembroComisionSeeder extends Seeder
{
    public function run(): void
    {
        $miembrosComision =[
            [
                'idUsuario' => 3, 
                'idComision' => 1, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.DIR'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Presidente',
                'responsable' => 1,
            ],
            [
                'idUsuario' => 42, 
                'idComision' => 1, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => '',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 6, 
                'idComision' => 1, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI_VP'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => '',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 24, 
                'idComision' => 1, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PAS'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => '',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 27, 
                'idComision' => 1, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.EST'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => '',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 43, 
                'idComision' => 1, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.EST'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => '',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 37, 
                'idComision' => 2, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Subdirector de Ordenación Académica y Estudiantes',
                'responsable' => 1,
            ],
            [
                'idUsuario' => 44, 
                'idComision' => 2, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => '',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 15, 
                'idComision' => 2, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI_VP'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => '',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 36, 
                'idComision' => 2, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => '',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 6, 
                'idComision' => 2, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI_VP'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => '',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 14, 
                'idComision' => 2, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.EST'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => '',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 45, 
                'idComision' => 2, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.EST'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => '',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 46, 
                'idComision' => 2, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.EST'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => '',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 47, 
                'idComision' => 2, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.EST'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => '',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 48, 
                'idComision' => 2, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.EST'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => '',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 49, 
                'idComision' => 2, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI_VP'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => '',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 34, 
                'idComision' => 3, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Subdirector de Relaciones Exteriores y Movilidad',
                'responsable' => 1,
            ],
            [
                'idUsuario' => 49, 
                'idComision' => 3, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor GIE',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 50, 
                'idComision' => 3, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor GIM',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 51, 
                'idComision' => 3, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesora GIEI',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 5, 
                'idComision' => 3, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI_VP'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor GII',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 52, 
                'idComision' => 3, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI_VP'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor MUII',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 53, 
                'idComision' => 3, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.EST'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor MUII',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 28, 
                'idComision' => 3, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.EST'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => '',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 34, 
                'idComision' => 4, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Subdirector Relaciones Exteriores y Movilidad',
                'responsable' => 1,
            ],
            [
                'idUsuario' => 55, 
                'idComision' => 4, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor por Grado en Ingeniería Eléctrica',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 56, 
                'idComision' => 4, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor por Grado en Ingeniería Electrónica Industrial',
                'responsable' => 0
            ],
            [
                'idUsuario' => 57, 
                'idComision' => 4, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor por Grado en Ingeniería Informática',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 58, 
                'idComision' => 4, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesora por Grado en Ingeniería Mecánica',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 59, 
                'idComision' => 4, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PAS'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => '',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 60, 
                'idComision' => 4, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.EST'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => '',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 61, 
                'idComision' => 4, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.EST'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => '',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 4, 
                'idComision' => 5, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI_VP'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Secretario EPSC',
                'responsable' => 1,
            ],
            [
                'idUsuario' => 62, 
                'idComision' => 5, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI_VP'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor GIE',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 35, 
                'idComision' => 5, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor GIEI',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 42, 
                'idComision' => 5, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor GIM',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 58, 
                'idComision' => 5, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor MII',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 11, 
                'idComision' => 5, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI_VP'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor GII',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 63, 
                'idComision' => 5, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PAS'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => '',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 26, 
                'idComision' => 5, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.EST'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => '',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 49, 
                'idComision' => 6, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Presidente',
                'responsable' => 1,
            ],
            [
                'idUsuario' => 6, 
                'idComision' => 6, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI_VP'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => '',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 55, 
                'idComision' => 6, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => '',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 62, 
                'idComision' => 6, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => '',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 51, 
                'idComision' => 7, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Presidente',
                'responsable' => 1,
            ],
            [
                'idUsuario' => 7, 
                'idComision' => 7, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI_VP'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => '',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 56, 
                'idComision' => 7, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => '',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 64, 
                'idComision' => 7, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => '',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 65, 
                'idComision' => 8, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Presidente',
                'responsable' => 1,
            ],
            [
                'idUsuario' => 66, 
                'idComision' => 8, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => '',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 42, 
                'idComision' => 8, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => '',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 67, 
                'idComision' => 8, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Presidente',
                'responsable' => 1,
            ],
            [
                'idUsuario' => 5, 
                'idComision' => 9, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI_VP'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Presidente',
                'responsable' => 1,
            ],
            [
                'idUsuario' => 68, 
                'idComision' => 9, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => '',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 11, 
                'idComision' => 9, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI_VP'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => '',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 1, 
                'idComision' => 9, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI_VP'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => '',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 52, 
                'idComision' => 10, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Presidente',
                'responsable' => 1,
            ],
            [
                'idUsuario' => 64, 
                'idComision' => 10, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => '',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 44, 
                'idComision' => 10, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => '',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 42, 
                'idComision' => 10, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => '',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 3, 
                'idComision' => 11, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI_VP'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Presidente',
                'responsable' => 1,
            ],
            [
                'idUsuario' => 4, 
                'idComision' => 11, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI_VP'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Secretario',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 69, 
                'idComision' => 11, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor área Tecnología Electrónica',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 56, 
                'idComision' => 11, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor área Electrónica',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 70, 
                'idComision' => 11, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor área Arquitectura y Tecnología de Computadores',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 71, 
                'idComision' => 11, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor área Organización de Empresas',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 72, 
                'idComision' => 11, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor área Estadística e Inv. Operativa',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 73, 
                'idComision' => 11, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor área Filología Inglesa',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 15, 
                'idComision' => 11, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI_VP'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor área Física Aplicada',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 74, 
                'idComision' => 11, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor área Ciencias de la Computación e I.A.',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 75, 
                'idComision' => 11, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor área Ing. de Sistemas y Automática',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 76, 
                'idComision' => 11, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor área Expresión Gráfica en la Ing.',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 49, 
                'idComision' => 11, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor área Ing. Eléctrica',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 9, 
                'idComision' => 11, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI_VP'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor área Proyectos de Ingeniería',
                'responsable' => 0,
            ],
            [
                'idUsuario' =>83, 
                'idComision' => 11, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor área Matemática Aplicada',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 77, 
                'idComision' => 11, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor área Ing. Mecánica',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 42, 
                'idComision' => 11, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor área Mecánica de Medios Continuos y T.E.',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 67, 
                'idComision' => 11, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor área Ing. Procesos Fabricación',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 50, 
                'idComision' => 11, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor área Ciencia de los Materiales e Ing. Met.',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 65, 
                'idComision' => 11, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor área Máquinas y Motores Térmicos',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 78, 
                'idComision' => 11, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor área Máquinas y Motores Térmicos',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 79, 
                'idComision' => 11, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => '',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 3, 
                'idComision' => 13, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI_VP'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Presidente',
                'responsable' => 1,
            ],
            [
                'idUsuario' => 4, 
                'idComision' => 13, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI_VP'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Secretario',
                'responsable' => 1,
            ],
            [
                'idUsuario' => 10, 
                'idComision' => 13, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI_VP'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor área Tecnología Electrónica',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 38, 
                'idComision' => 13, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor área Electrónica',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 71, 
                'idComision' => 13, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor área Organización de Empresas',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 72, 
                'idComision' => 13, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor área Estadística e Inv. Operativa',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 73, 
                'idComision' => 13, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor área Filología Inglesa',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 80, 
                'idComision' => 13, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor área Física Aplicada',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 8, 
                'idComision' => 13, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI_VP'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor área Física Aplicada',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 37, 
                'idComision' => 13, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor área Ing. Eléctrica',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 35, 
                'idComision' => 13, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor área Ing. de Sistemas y Automática',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 33, 
                'idComision' => 13, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor área Expresión Gráfica en la Ing.',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 66, 
                'idComision' => 13, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor área Proyectos de Ingeniería',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 81, 
                'idComision' => 13, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor área Matemática Aplicada',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 64, 
                'idComision' => 13, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor área Ing. Mecánica',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 82, 
                'idComision' => 13, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor área Mecánica de Medios Continuos y T.E.',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 36, 
                'idComision' => 13, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor área Ing. Procesos Fabricación',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 50, 
                'idComision' => 13, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor área Ciencia de los Materiales e Ing. Met.',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 65, 
                'idComision' => 13, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor área Máquinas y Motores Térmicos',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 78, 
                'idComision' => 13, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor área Química Orgánica',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 84, 
                'idComision' => 13, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.EST'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => '',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 3, 
                'idComision' => 14, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI_VP'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Presidente',
                'responsable' => 1,
            ],
            [
                'idUsuario' => 4, 
                'idComision' => 14, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI_VP'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Secretario',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 57, 
                'idComision' => 14, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor área Tecnología Electrónica',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 85, 
                'idComision' => 14, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor área Arquitectura y Tecnología de Computadores',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 41, 
                'idComision' => 14, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor área Organización de Empresas',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 72, 
                'idComision' => 14, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor área Estadística e Inv. Operativa',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 73, 
                'idComision' => 14, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor área Filología Inglesa',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 86, 
                'idComision' => 14, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor área Física Aplicada',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 87, 
                'idComision' => 14, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor área Ciencias de la Computación e I.A.',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 76, 
                'idComision' => 14, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor área Expresión Gráfica en la Ing.',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 5, 
                'idComision' => 14, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI_VP'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor área Proyectos de Ingeniería',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 32, 
                'idComision' => 14, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor área Matemática Aplicada',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 31, 
                'idComision' => 14, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.EST'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => '',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 88, 
                'idComision' => 15, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Presidente',
                'responsable' => 1,
            ],
            [
                'idUsuario' => 4, 
                'idComision' => 15, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI_VP'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Secretario',
                'responsable' => 1,
            ],
            [
                'idUsuario' => 89, 
                'idComision' => 15, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor área Tecnología Electrónica',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 90, 
                'idComision' => 15, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor área Electrónica',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 91, 
                'idComision' => 15, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor área Arquitectura y Tecnología de Computadores',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 41, 
                'idComision' => 15, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor área Organización de Empresas',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 55, 
                'idComision' => 15, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor área Ing. de Sistemas y Automática',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 92, 
                'idComision' => 15, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor área Ing. Eléctrica',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 93, 
                'idComision' => 15, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor área Proyectos de Ingeniería',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 77, 
                'idComision' => 15, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor área Ing. Mecánica',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 82, 
                'idComision' => 15, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor área Mecánica de Medios Continuos y T.E.',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 52, 
                'idComision' => 15, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor área Ing. Procesos Fabricación',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 39, 
                'idComision' => 15, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor área Máquinas y Motores Térmicos',
                'responsable' => 0,
            ],
            [
                'idUsuario' => 94, 
                'idComision' => 15, 
                'representacion' => config('constants.REPRESENTACIONES.COMISION.PDI'),
                'fechaTomaPosesion' => '2022-12-02',
                'cargo' => 'Profesor área Ing. Química',
                'responsable' => 0,
            ],
        ];

        foreach($miembrosComision as $m){
            $miembro = new MiembroComision();
            $miembro->idUsuario = $m['idUsuario'];
            $miembro->idComision = $m['idComision'];
            $miembro->fechaTomaPosesion = $m['fechaTomaPosesion'];
            $miembro->fechaCese = null;
            $miembro->idRepresentacion = $m['representacion'];
            isset($m['cargo']) ? $miembro->cargo = $m['cargo'] : null;
            $miembro->responsable = $m['responsable'];
            $miembro->save();
        }
        // Se hace así para que haga un commit en cada creación y permita no repetir miembros
        for($i=0; $i<10; $i++){
            MiembroComision::factory()->count(1)->create();
        }
    }
}
