import axios from "axios";

import { ENDPOINT_MIEMBROSCOMISION_UPDATE_BBDD,ENDPOINT_MIEMBROSCOMISION_GET_BBDD, ENDPOINT_MIEMBROSCOMISION_DELETE_BBDD, ENDPOINT_MIEMBROSCOMISION_ADD_BBDD, ENDPOINT_MIEMBROSCOMISION_VALIDATE_BBDD} from "./apiConst";

function DELETE_MIEMBROSCOMISION_AXIOS() {
    return axios(ENDPOINT_MIEMBROSCOMISION_DELETE_BBDD);
}

function GET_MIEMBROSCOMISION_AXIOS() {
    return axios(ENDPOINT_MIEMBROSCOMISION_GET_BBDD);
}

function UPDATE_MIEMBROSCOMISION_AXIOS() {
    return axios(ENDPOINT_MIEMBROSCOMISION_UPDATE_BBDD);
}

function ADD_MIEMBROSCOMISION_AXIOS() {
    return axios(ENDPOINT_MIEMBROSCOMISION_ADD_BBDD);
}

function VALIDATE_MIEMBROSCOMISION_AXIOS() {
    return axios(ENDPOINT_MIEMBROSCOMISION_VALIDATE_BBDD);
}

export {
    DELETE_MIEMBROSCOMISION_AXIOS,
    GET_MIEMBROSCOMISION_AXIOS,
    UPDATE_MIEMBROSCOMISION_AXIOS,
    ADD_MIEMBROSCOMISION_AXIOS,
    VALIDATE_MIEMBROSCOMISION_AXIOS,
}