const MIEMBROSCOMISION_DELETE_URL = "miembro_comision/delete"
const MIEMBROSCOMISION_GET_URL = "miembro_comision/get"
const MIEMBROSCOMISION_UPDATE_URL = "miembro_comision/update"
const MIEMBROSCOMISION_ADD_URL = "miembro_comision/add"
const MIEMBROSCOMISION_VALIDATE_URL = "miembro_comision/validate"

export {
    MIEMBROSCOMISION_DELETE_URL,
    MIEMBROSCOMISION_GET_URL,
    MIEMBROSCOMISION_UPDATE_URL,
    MIEMBROSCOMISION_ADD_URL,
    MIEMBROSCOMISION_VALIDATE_URL,
}