const MIEMBROSCOMISION_DELETE_URL = "miembro_comision/delete"
const MIEMBROSCOMISION_GET_URL = "miembro_comision/get"
const MIEMBROSCOMISION_UPDATE_URL = "miembro_comision/update"

export {
    MIEMBROSCOMISION_DELETE_URL,
    MIEMBROSCOMISION_GET_URL,
    MIEMBROSCOMISION_UPDATE_URL
}