import axios from "axios";

import { ENDPOINT_REPRESENTACION_UPDATE_BBDD,ENDPOINT_REPRESENTACION_GET_BBDD, ENDPOINT_REPRESENTACION_DELETE_BBDD, ENDPOINT_REPRESENTACION_GETALL_BBDD} from "./apiConst";

function DELETE_REPRESENTACION_AXIOS() {
    return axios(ENDPOINT_REPRESENTACION_DELETE_BBDD);
}

function GET_REPRESENTACION_AXIOS() {
    return axios(ENDPOINT_REPRESENTACION_GET_BBDD);
}

function UPDATE_REPRESENTACION_AXIOS() {
    return axios(ENDPOINT_REPRESENTACION_UPDATE_BBDD);
}

function GETALL_REPRESENTACION_AXIOS() {
    return axios(ENDPOINT_REPRESENTACION_GETALL_BBDD);
}

export {
    DELETE_REPRESENTACION_AXIOS,
    GET_REPRESENTACION_AXIOS,
    UPDATE_REPRESENTACION_AXIOS,
    GETALL_REPRESENTACION_AXIOS
}