const MIEMBROSJUNTA_DELETE_URL = "miembro_junta/delete"
const MIEMBROSJUNTA_GET_URL = "miembro_junta/get"
const MIEMBROSJUNTA_UPDATE_URL = "miembro_junta/update"
const MIEMBROSJUNTA_GETBYCENTRO_URL = "miembros_junta/getbycentro"
const MIEMBROSJUNTA_ADD_URL = "miembro_junta/add"
const MIEMBROSJUNTA_VALIDATE_URL = "miembro_junta/validate"

export {
    MIEMBROSJUNTA_DELETE_URL,
    MIEMBROSJUNTA_GET_URL,
    MIEMBROSJUNTA_UPDATE_URL,
    MIEMBROSJUNTA_GETBYCENTRO_URL,
    MIEMBROSJUNTA_ADD_URL,
    MIEMBROSJUNTA_VALIDATE_URL,
}