import axios from "axios";

import { ENDPOINT_MIEMBROSGOBIERNO_UPDATE_BBDD,ENDPOINT_MIEMBROSGOBIERNO_GET_BBDD, ENDPOINT_MIEMBROSGOBIERNO_DELETE_BBDD} from "./apiConst";

function DELETE_MIEMBROSGOBIERNO_AXIOS() {
    return axios(ENDPOINT_MIEMBROSGOBIERNO_DELETE_BBDD);
}

function GET_MIEMBROSGOBIERNO_AXIOS() {
    return axios(ENDPOINT_MIEMBROSGOBIERNO_GET_BBDD);
}

function UPDATE_MIEMBROSGOBIERNO_AXIOS() {
    return axios(ENDPOINT_MIEMBROSGOBIERNO_UPDATE_BBDD);
}

export {
    DELETE_MIEMBROSGOBIERNO_AXIOS,
    GET_MIEMBROSGOBIERNO_AXIOS,
    UPDATE_MIEMBROSGOBIERNO_AXIOS,
}