import axios from "axios";

import { ENDPOINT_MIEMBROSGOBIERNO_UPDATE_BBDD,ENDPOINT_MIEMBROSGOBIERNO_GET_BBDD, ENDPOINT_MIEMBROSGOBIERNO_DELETE_BBDD, ENDPOINT_MIEMBROSGOBIERNO_GETBYCENTRO_BBDD, ENDPOINT_MIEMBROSGOBIERNO_ADD_BBDD} from "./apiConst";

function DELETE_MIEMBROSGOBIERNO_AXIOS() {
    return axios(ENDPOINT_MIEMBROSGOBIERNO_DELETE_BBDD);
}

function GET_MIEMBROSGOBIERNO_AXIOS() {
    return axios(ENDPOINT_MIEMBROSGOBIERNO_GET_BBDD);
}

function UPDATE_MIEMBROSGOBIERNO_AXIOS() {
    return axios(ENDPOINT_MIEMBROSGOBIERNO_UPDATE_BBDD);
}

function GETBYCENTRO_MIEMBROSGOBIERNO_AXIOS() {
    return axios(ENDPOINT_MIEMBROSGOBIERNO_GETBYCENTRO_BBDD);
}

function ADD_MIEMBROSGOBIERNO_AXIOS() {
    return axios(ENDPOINT_MIEMBROSGOBIERNO_ADD_BBDD);
}

export {
    DELETE_MIEMBROSGOBIERNO_AXIOS,
    GET_MIEMBROSGOBIERNO_AXIOS,
    UPDATE_MIEMBROSGOBIERNO_AXIOS,
    GETBYCENTRO_MIEMBROSGOBIERNO_AXIOS,
    ADD_MIEMBROSGOBIERNO_AXIOS
}